#ifndef SPLINT_ABI_H
#define SPLINT_ABI_H

/* Stable Ring 3 ABI. Keep existing numbers unchanged. */
#define SPLINT_ABI_VERSION 1

#define SPLINT_SYS_WRITE 1
#define SPLINT_SYS_EXIT 2
#define SPLINT_SYS_OPEN 3
#define SPLINT_SYS_READ 4
#define SPLINT_SYS_CLOSE 5
#define SPLINT_SYS_GETPID 6
#define SPLINT_SYS_SPAWN 7
#define SPLINT_SYS_WAIT 8
#define SPLINT_SYS_DUP2 9
#define SPLINT_SYS_PIPE 10
#define SPLINT_SYS_SPAWN_ACTIONS 11
#define SPLINT_SYS_LIST 12
#define SPLINT_SYS_MEMORY_INFO 13
#define SPLINT_SYS_UPTIME 14
#define SPLINT_SYS_PROCESS_INFO 15
#define SPLINT_SYS_BRK 16
#define SPLINT_SYS_YIELD 17
#define SPLINT_SYS_SLEEP 18
#define SPLINT_SYS_SEEK 19
#define SPLINT_SYS_FSYNC 20
#define SPLINT_SYS_UNLINK 21
#define SPLINT_SYS_RENAME 22
#define SPLINT_SYS_LOG_READ 23
#define SPLINT_SYS_STAT 24
#define SPLINT_SYS_UNAME 25
#define SPLINT_SYS_TRUNCATE 26
#define SPLINT_SYS_MKDIR 27
#define SPLINT_SYS_RMDIR 28
#define SPLINT_SYS_CHMOD 29
#define SPLINT_SYS_GETUID 30
#define SPLINT_SYS_POLL 31
#define SPLINT_SYS_CLOCK_GET 32
#define SPLINT_SYS_UDP_OPEN 33
#define SPLINT_SYS_UDP_SEND 34
#define SPLINT_SYS_UDP_RECEIVE 35
#define SPLINT_SYS_NETWORK_CONFIG 36
#define SPLINT_SYS_WALL_CLOCK 37
#define SPLINT_SYS_STAT_TIMESTAMPS 38
#define SPLINT_SYS_GETPGRP 39
#define SPLINT_SYS_SETPGID 40
#define SPLINT_SYS_COUNT 40

#define SPLINT_ABI_MAX_IO 4096
#define SPLINT_ABI_MAX_PATH 127
#define SPLINT_ABI_MAX_ARGUMENTS 8
#define SPLINT_ABI_MAX_ACTIONS 8

#endif
